### ISSUE TITLE
Only support for version 1 - 9

### ISSUE THREAD

**Issue by ghost** [RIDGIDSoftwareSolutions/versioned-rest-api#9]
When I use the example project, and I make the "currentApiVersion" = 12. Without making any other changes , the routing seems to break from "api/v10/Examples/" onwards.

![error message](https://cloud.githubusercontent.com/assets/15113583/12285873/7e54c2e8-b9c7-11e5-9897-59c8fa42905d.png)

**Comment by jakejgordon** [comment]
Good catch! Will fix it soon (unless you plan to).

**Comment by ghost** [comment]
I resolved the issue on my branch: https://github.com/jsakkie/versioned-rest-api.git

Please have a look and let me know if this will work

**Comment by jakejgordon** [comment]
@jsakkie darn, I just pushed up the fix! You at least added another test so if you want to merge in my (identical) fix and then submit a pull request I can at least pull in your tests. Thanks for contributing!

I also broke the appveyor build when I updated to nUnit 3. Will try to fix this tonight. I also need to push latest version to nuGet -- will try to do that tonight as well.

**Comment by ghost** [comment]
Thanks :-)
